version: "3.7"
services:
  php:
    image: php-fpm-custom
    build:
      dockerfile: php.Dockerfile 
      context: .
    volumes:
      - ./public_html:/public_html
    networks:
      - lamp

  nginx:
     image: nginx:alpine
     ports:
       - 8890:80
     volumes:
       - ./nginx/site.conf:/etc/nginx/conf.d/default.conf 
       - ./public_html:/public_html
     networks:
       - lamp

  mysql:
    image: mysql:5
    env_file: /opt/secrets.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - lamp

  ftp:
    image: delfer/alpine-ftp-server
    env_file: /opt/secrets.env
    ports:
      - "8021:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./public_html:/public_html

networks:
  lamp:
    external: true
